Add Layers
Beef-Community-Project/Steel pull request #13
Opened 2020-08-01 14:11 UTC by RogueMacro

2020-08-01 17:19 UTC, jamesaorson reviewed
Can we have a quick explanation of what this is for?

2020-08-01 17:23 UTC, jamesaorson requested changes
Shouldn't a LayerStaxk provide a proper pop and push? Since it is for ordering events, just allowing people to add and remove from arbitrary locations doesn't provide anything valuable.

2020-08-01 18:53 UTC, RogueMacro commented
I will adress this. Quick explanation: there will be a layer for ie the game world, one for ui and so on. When an event occurs it gets passed down the layer stack and layers can consume events.

2020-08-01 20:02 UTC, jamesaorson requested changes

2020-08-01 20:02 UTC, JamesOrson commented on Engine/src/LayerStack.bf
> +		}
Shouldn't these use `PopBack()` if they are gonna act as a Stack?

2020-08-02 22:14 UTC, RogueMacro commented
Accidentally made another pull request, just move over there instead: https://github.com/Beef-Community-Project/Steel/pull/18

2020-08-02 22:14 UTC, closed without merging