Math library
Beef-Community-Project/Steel pull request #30
Opened 2020-08-11 17:59 UTC by Fusioon

Finally made the library somehow usable. It still needs thorough testing so use with care. Some methods and operator overloads are not yet implemented but what is implemented should be enough for now. 

Closes #23

2020-08-12 18:41 UTC, RogueMacro commented
If I wanted to use a Vector3 then I would have to use Vector3<float> for example?

2020-08-12 18:59 UTC, Fusioon commented
> @Fusioon  If I wanted to use a Vector3 then I would have to use Vector3\<float> for example?

Every type can be used without specifying generic parameter. When used without generic it will use Vector3\<float> , this behaviour is defined with typealiases in Typealias.bf

2020-08-12 19:42 UTC, RogueMacro requested changes
I don't even understand half of the constraints

2020-08-12 19:42 UTC, RogueMacro commented on Engine/src/Math/Matrix33.bf
> +									 0,0,0);
What is this indentation?

2020-08-12 19:42 UTC, RogueMacro commented on Engine/src/Math/Matrix33.bf
> +			}
Weird indentation here too.

2020-08-12 19:42 UTC, RogueMacro commented on Engine/src/Math/Quaternion.bf
> +			if(axis.LengthSquared > (T)0.05)
Space between if and (

2020-08-12 19:42 UTC, RogueMacro commented on Engine/src/Math/Vector2.bf
> +			if(div == 0) return 0;
Space between if and (

2020-08-12 19:42 UTC, RogueMacro commented on Engine/src/Math/Vector4.bf
> +			if(div == 0) return 0;
Space between if and (

2020-08-12 19:42 UTC, RogueMacro commented on Engine/src/Math/Vector3.bf
> +			if(div == 0) return 0;
Space between if and (

2020-08-12 19:43 UTC, RogueMacro commented on Engine/src/Math/Matrix33.bf
> +			}
I mean some lines above this

2020-08-13 13:14 UTC, RogueMacro approved these changes

2020-08-13 13:16 UTC, merged